name: Deno CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-deno:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: [v1.10.3]
        node-version: [16.x]
        build-how: ["cdn"]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Deno ${{ matrix.deno }}
        run:
          curl -fsSL https://deno.land/x/install/install.sh | sudo
          DENO_INSTALL=/usr/local sh -s ${{ matrix.deno }}
      - run: npm install
      - run: node ./tools/build.js -t ${{ matrix.build-how }}
      - name: Run tests
        run: deno test test/deno/index.ts
